server:
  port: 8081
spring:
  main:
    web-application-type: REACTIVE
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/example
    username: dbuser
    password: dbpassword
logging:
  level:
    root: INFO
    com.example.spring_reactive: DEBUG
db:
  schema:
    location: db/schema.sql
