openapi: "3.0.3"
info:
  version: 1.0.0
  title: Example reactive API
servers:
  - url: http://localhost:8080
paths:
  /things:
    get:
      summary: List things
      description: This takes some time
      operationId: listThings
      tags:
        - things
      parameters:
        - name: nbThings
          in: query
          description: How many things to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A list of things
          content:
            text/event-stream:
              schema:
                $ref: "#/components/schemas/Things"
        default:
          description: Unexpected error
          content:
            text/event-stream:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create new things
      description: This takes some time
      operationId: createThings
      tags:
        - things
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Things'
      responses:
        '201':
          description: Creation successful
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Thing:
      type: object
      required:
        - content
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
    Things:
      type: array
      items:
        $ref: "#/components/schemas/Thing"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
